# docker-compose.yml
version: '3.9'
services:
  ticket:
    image: kasd0134/amusementservice:ticketmanagement
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017