apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
      - name: ticket
        image: kasd0134/amusementservice:ticketmanagement
        ports:
        - containerPort: 8000
