apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: ticket
  name: ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ticket
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/ticketmanagement-default: "true"
        io.kompose.service: ticket
    spec:
      containers:
        - args:
            - uvicorn
            - main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          image: kasd0134/amusementservice:1.0
          name: ticket
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: ticket-claim0
      restartPolicy: Always
      volumes:
        - name: ticket-claim0
          persistentVolumeClaim:
            claimName: ticket-claim0
