# .github/workflows/build.yml
name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_service1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r TicketManagement/requirements.txt
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: TicketManagement
        push: true
        tags: my-registry/service1:latest

  